### PR TITLE
Prevent token collection corruption - little help

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Comment by keradus** [comment]
About BracesFixer - problem is with comments that have trailing whitespaces, and we have special transformer to split that whitespace into next T_WHITESPACE token - WhitespacyCommentTransformer.

**Comment by keradus** [comment]
I suggest to temporary recreate token collection on the end of `BracesFixer::fix` method, and remove it on 2.0 branch.
What do you think?

**Comment by keradus** [comment]
ping @stof

**Comment by stof** [comment]
@keradus couldn't we create the comment token properly according to the way we transform things instead ?

**Comment by keradus** [comment]
`BracesFixer` is big, and figuring it out will takes time.
I would simply take care of it on 2.0 line.

Ref #3

**Pull request merged**
